jobs:
  build:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Start
        uses: actions/checkout@v2
      - name: Download Tools
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./main/ci

name: Run

on:
  schedule:
    - cron: "55 */6 * * *"
